<?php

declare(strict_types=1);

/**
 * @file
 * Provides an investigation documents entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function investigation_documents_theme(): array {
  return [
    'investigation_documents' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for investigation documents templates.
 *
 * Default template: investigation-documents.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the investigation documents information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_investigation_documents(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function investigation_documents_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish investigation documentss.
      $storage = \Drupal::entityTypeManager()->getStorage('investigation_documents');
      $investigation_documents_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($investigation_documents_ids) as $investigation_documents) {
        $investigation_documents->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize investigation documentss.
      $storage = \Drupal::entityTypeManager()->getStorage('investigation_documents');
      $investigation_documents_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($investigation_documents_ids) as $investigation_documents) {
        $investigation_documents->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function investigation_documents_user_predelete(UserInterface $account): void {
  // Delete investigation documentss that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('investigation_documents');
  $investigation_documents_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($investigation_documents_ids)
  );
}
