<?php

declare(strict_types=1);

/**
 * @file
 * Provides a report-generator entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function ReportGenerator_theme(): array {
  return [
    'report-generator' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for report-generator templates.
 *
 * Default template: report-generator.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the report-generator information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preReportGenerator_ReportGenerator(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function ReportGenerator_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish report-generator.
      $storage = \Drupal::entityTypeManager()->getStorage('report-generator');
      $ReportGenerator_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($ReportGenerator_ids) as $ReportGenerator) {
        $ReportGenerator->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize ReportGenerator.
      $storage = \Drupal::entityTypeManager()->getStorage('ReportGenerator');
      $ReportGenerator_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($ReportGenerator_ids) as $ReportGenerator) {
        $ReportGenerator->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function ReportGenerator_user_predelete(UserInterface $account): void {
  // Delete report-generator that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('ReportGenerator');
  $ReportGenerator_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($ReportGenerator_ids)
  );
  // Delete old revisions.
  $ReportGenerator_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  foreach (array_keys($ReportGenerator_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}
